kind: pipeline
name: build-test-and-publish

steps:
- name: build-test-and-publish
  image: mcr.microsoft.com/dotnet/sdk:6.0
  environment:
    NUGET_SERVER_ADRESS:
      from_secret: NUGET_SERVER_ADRESS
    NUGET_SERVER_KEY:
      from_secret: NUGET_SERVER_KEY
  commands:
    - sed -i 's/>1.0.0</>${DRONE_TAG}</g' Dysnomia.Common.WebAPIWrapper/Dysnomia.Common.WebAPIWrapper.csproj
    - dotnet build Dysnomia.Common.WebAPIWrapper.sln -c Release
    - dotnet pack Dysnomia.Common.WebAPIWrapper.sln -c Release
    - dotnet nuget push -s $NUGET_SERVER_ADRESS -k $NUGET_SERVER_KEY $(ls /drone/src/Dysnomia.Common.WebAPIWrapper/bin/Release/*.nupkg | head -1)
  when:
    event:
    - tag

- name: docker
  image: plugins/docker
  settings:
    repo: dysnomia/dysnomia-common-webapiwrapper
    dockerfile: Dockerfile
    tags: ${DRONE_BRANCH//\//-}
    dry_run: true
    pull-image: false
  environment:
    PLUGIN_PULL_IMAGE: false
    DRONE_BRANCH: ${DRONE_BRANCH}
    SONAR_HOST: 
      from_secret: SONAR_HOST
    SONAR_TOKEN: 
      from_secret: SONAR_TOKEN
  settings:
    build_args_from_env:
      - DRONE_BRANCH
      - SONAR_HOST
      - SONAR_TOKEN
  when:
    event:
    - push

- name: discord
  pull: default
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: WEBHOOK_ID
    webhook_token:
      from_secret: WEBHOOK_TOKEN
    message: >
      {{#success build.status}}
        Build **{{repo.name}}** for tag **${DRONE_TAG}** succeeded.
      {{else}}
        Build **{{repo.name}}** for tag **${DRONE_TAG}** failed.
      {{/success}}
  when:
    event:
    - tag

    status: 
    - changed
    - failure
    - success
